[env:esp32-c3-super-mini]
platform = espressif32@~6.7.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
upload_flags = 
    --no-stub
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    earlephilhower/ESP8266Audio@1.9.7
    tzapu/WiFiManager@^2.0.17
